package org.cdac.ankit.hibernate.test;

import java.util.Date;

import org.cdac.ankit.hibernate.model.Address;
import org.cdac.ankit.hibernate.model.UserDetail;
import org.cdac.ankit.hibernate.model.Vehicle;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

public class HibernateTest {
	
	public static void main(String[] args){
		UserDetail user=new UserDetail();
		//user.setUserId("210602"); Generated BY hypbernate using @GeneratedValue
		user.setUserName("Ankit Kumar Nayak");
		user.setContanctNumber("9664861082");
		user.setEmailId("ankitkumarnayak@cdac.in");
		user.setJoinDate(new Date());
		
		Address homeAdd=new Address();
		homeAdd.setCity("Kharghar");
		homeAdd.setStreet("Rain Tree Marg");
		homeAdd.setState("Maharashtra");
		homeAdd.setCountry("India");
		
		user.setHomeAddress(homeAdd);

		Address officeAddress=new Address();
		officeAddress.setCity("Kharghar");
		officeAddress.setStreet("Rain Tree Marg");
		officeAddress.setState("Maharashtra");
		officeAddress.setCountry("India");
		
		user.setHomeAddress(officeAddress);
		
		user.getPreviousHomeAddresses().add(homeAdd);
		user.getPreviousHomeAddresses().add(officeAddress);
		
		
		Vehicle v1=new Vehicle();
		v1.setModelId("MOD01");
		v1.setVechicleNumber("MH 0002");
		v1.setUser(user);

		Vehicle v2=new Vehicle();
		v2.setModelId("MOD01");
		v2.setVechicleNumber("MH 0003");
		v2.setUser(user);
		
		user.getVechicles().add(v1);
		user.getVechicles().add(v2);
		
		
		SessionFactory factory=new Configuration().configure().buildSessionFactory();
		Session session=factory.openSession();
		session.beginTransaction();
		// session.save(user);  // it should not be used when cascade type is PERSIST
		session.persist(user);
		session.getTransaction().commit();
		session.close();
		/*
		session=factory.openSession();
		session.beginTransaction();
		UserDetail userDetail=(UserDetail)session.get(UserDetail.class, "210602");
		System.out.println(userDetail);*/
		
		
	}

}
